### ISSUE TITLE
GeoIP2 plugin: bad or corrupted GeoLite2 database found.

### ISSUE THREAD

**Issue by giveup** [Micdu70/geoip2-rutorrent#1]
I am sure the geo DB is correctly.
php 7.2.12-1
latest rutorrent and geoip2 plugin

**Comment by notDavid** [comment]
I get the same error (in nginx), that error seems to be caused by the 'phar' extension not loading: https://github.com/Micdu70/geoip2-rutorrent/blob/ce25be70c7767d67b6e5ec7cb118b36b62c93528/init.php#L13

**Comment by notDavid** [comment]
Fyi, i managed to log the php error that was causing this error message:
`The gmp or bcmath extension must be installed to read this database.`

I think i fixed it by running:
`apt install php7.3-bcmath` and `systemctl restart lighttpd.service`

**Comment by Micdu70** [comment]
@notDavid Thanks for this info! Plugin has been updated and now checks if "bcmath" PHP extension is installed and loaded + README.md updated too. =)

**Comment by notDavid** [comment]
@Micdu70 👍🏼🙂
