### ISSUE TITLE
FileUtil not found in init.php

### ISSUE THREAD

**Issue by phillipapa** [Micdu70/geoip2-rutorrent#5]
Got a stack trace with this message:
`2022/05/23 21:41:38 [error] 25415#25415: *13193 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'FileUtil' not found in /<PATH>/init.php:11`

All required extensions are enabled: json, phar, bcmath (PHP 7)

Edit: original geoip is disabled
I kinda had a hunch that the latest database is the one causing this, perhaps? the db I used is GeoLite2-City version 20220522

This seems to be happening in 3.9 (no clue about 3.10)
Not sure which rutorrent commit since this is a one click installation from a server

**Comment by Micdu70** [comment]
The 'master' branch of my geoip2 plugin is only working with the rutorrent's 'master' branch or with ruTorrent v4.0-beta.2 (pre-release)

If you are using ruTorrent v3.10 (or below), you must download the Stable version of my geoip2 plugin by using the 'Stable' branch or by downloading the latest 'Stable' release (zip file) here => https://github.com/Micdu70/geoip2-rutorrent/releases
